name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true # Caches Go modules for faster builds

      - name: Install dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --enable-all --exclude-use-default=false

      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out
          flags: unittests

      - name: Build the application
        run: go build -v ./...

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-build
          path: ./ # Adjust path if needed
